### ISSUE TITLE
Question: Uninstall procedure

### ISSUE THREAD

**Issue by asfarley** [hfiref0x/DSEFix#13]
Just a couple of questions about the intended usage of this application:

1) Does dsefix.exe need to be executed again if the PC is restarted, or is the effect removed upon restart?
2) If the PC has been restarted, does 'dsefix.exe -e' have any effect? 
3) If I had previously used dsefix.exe (but now I want to completely remove it), what is the procedure?

**Comment by SmoLL-iCe** [comment]
Dsefix is an exploit that uses the virtualbox driver so that it can load non-signed drivers digitally, it only works during the current session of the system, if restarting loses all effect, since the virtualbox driver is stopped.
if you want to remove it completely is just delete the executable, since the driver that is installed is a normal driver of the VBox, it has no harmful effect, but in windows 10 after a while, the patchguard detects this anomaly and causes BSDO.

**Comment by hfiref0x** [comment]
@SmoLL-iCe answer is correct.
