### ISSUE TITLE
CRITICAL_STRUCTURE_CORRUPTION

### ISSUE THREAD

**Issue by nClarke0101** [hfiref0x/DSEFix#2]
Hi thanks for posting this.

I just want to report a error
i have used this in a virtual box with windows 8.1 x64
I sometimes get a bluescreen about CRITICAL_STRUCTURE_CORRUPTION (CI.dll)

I'm not sure if its because my virtualbox windows install is corrupt or if its caused from not setting something with this.

I always make sure i re enable DSE about 30 seconds after i disable it an load up my driver.

**Comment by hfiref0x** [comment]
This is KPP (PatchGuard) BSOD. This means you didn't restored DSE state in reasonable period of time and KPP was able to identify modification. Normally you should immediatelly restore DSE state after loading unsigned driver - 1-5 sec max.

**Comment by nClarke0101** [comment]
thats weird because i do, do it right after i have done everything so it would be in under 5 seconds

**Comment by hfiref0x** [comment]
The problem with KPP is that we don't know when it will check this variable. It can do it in 5 msecs after we zeroed it, or after 5 minutes. The possible solution is to boot into Debug mode to turn KPP off, however this will also require SecureBoot turning off, if you have it. This variant is a very bad from security perspective, because it will basically turn off two significant Windows protection technologies. DSEFix is dirty system hack, so it is unstable by design.

**Comment by nClarke0101** [comment]
I just checked with timers.
15 - 200 milliseconds is the period that i have DSE disabled for.
i would get the bluescreen like 5 - 10 minutes after i have disabled an enabled

could it be something else messing with the virtualbox?
I don't back up any vBoxDrv like you do, since im installing my Driver at a different place.
Could that have anything to do with it? since i start a vboxdrv without checking if ones active?

edit:
oh ok that makes more sense.

**Comment by hfiref0x** [comment]
Also note that Microsoft may (if not already) update ntos (without any notice in patch notes) for improving speed or increasing scan priority of system variables.
